name: Assets Report

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/assets/**'
  pull_request:
    paths:
      - 'docs/assets/**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Summarize largest assets
        run: |
          python - << 'PY'
import os
root = 'docs/assets'
files = []
for dp,_,fns in os.walk(root):
    for fn in fns:
        p = os.path.join(dp, fn)
        try:
            sz = os.path.getsize(p)
        except OSError:
            continue
        files.append((sz, p))
files.sort(reverse=True)
total = sum(sz for sz,_ in files)
count = len(files)
top = files[:20]
def fmt(b):
    return f"{b/1024/1024:.1f} MB" if b>=1024*1024 else f"{b/1024:.1f} KB"
lines = [
    "## Assets report\n",
    f"- Files: {count}\n\n",
    f"- Total size: {fmt(total)}\n\n",
    "- Top 20 assets by size:\n\n",
]
for i,(sz,p) in enumerate(top,1):
    lines.append(f"  {i}. {p} — {fmt(sz)}\n")
with open(os.environ['GITHUB_STEP_SUMMARY'], 'a', encoding='utf-8') as s:
    s.writelines(lines)
print('Wrote summary for', count, 'files')
PY
