name: Generate Related Data

concurrency:
  group: related-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/_posts/**'
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://download.pytorch.org/whl/cpu 'torch==2.5.1'
          pip install 'sentence-transformers==2.7.0'
      - name: Generate related.json (owner quick on push / embed missing on schedule)
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            RELATED_MODE=emb RELATED_ONLY_MISSING=1 python tools/generate_related.py
          else
            RELATED_MODE=owner python tools/generate_related.py
          fi
      - name: Generate search-index.json
        run: python tools/generate_search_index.py
      - name: Commit updated related/search files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: update related.json + search-index.json'
          file_pattern: |
            docs/_data/related.json
            docs/assets/search-index.json
          push_options: '--force-with-lease'
