name: Generate Related Data

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/_posts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install 'sentence-transformers==2.7.0'
      - name: Generate related.json
        run: python tools/generate_related.py
      - name: Commit updated related.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: update related.json (related repos)'
          file_pattern: docs/_data/related.json
