name: Pages (min)

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/pages-min.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      - id: deployment
        uses: actions/deploy-pages@v4
