name: RSS Smoke Check

on:
  workflow_run:
    workflows: ["Deploy Jekyll site"]
    types: ["completed"]

jobs:
  verify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check homepage
        run: |
          curl -fsS https://tom-doerr.github.io/repo_posts/
      - name: Check feed
        run: |
          FEED=https://tom-doerr.github.io/repo_posts/feed.xml
          # HEAD without piping to avoid broken-pipe exit 23
          curl -fsSI "$FEED" >/dev/null
      - name: Check first feed image is reachable
        run: |
          FEED=https://tom-doerr.github.io/repo_posts/feed.xml
          url=$(curl -fsS "$FEED" | awk -F 'src="' '/<img/{print $2; exit}' | cut -d '"' -f1)
          [ -n "$url" ] || (echo "No <img src> found in feed" && exit 1)
          # Retry a couple of times in case deploy propagation is lagging
          ok=0; for i in 1 2 3; do
            if curl -fsSI "$url" >/dev/null; then ok=1; break; fi
            sleep 3
          done
          [ "$ok" -eq 1 ] || (echo "Feed image not reachable" && exit 1)
      - name: Check a sample post has image and index link
        run: |
          BASE=https://tom-doerr.github.io/repo_posts
          curl -fsS "$BASE/2025/10/26/Tyrrrz-YoutubeExplode.html" | tee post.html >/dev/null
          grep -q 'class="post-image"' post.html
          grep -q 'View on index' post.html
      - name: Check a sample post shows Related repos
        run: |
          BASE=https://tom-doerr.github.io/repo_posts
          curl -fsS "$BASE/2025/10/26/Tyrrrz-YoutubeExplode.html" | tee post2.html >/dev/null
          grep -q 'Related repos' post2.html
          grep -q '<ul class="related-list">' post2.html
      - name: Check first related link returns 200
        run: |
          BASE=https://tom-doerr.github.io/repo_posts
          href=$(awk '/<ul class="related-list">/,/<\/ul>/' post2.html | grep -o 'href="[^"]*"' | head -n1 | sed -E 's/href="([^"]*)"/\1/')
          if [ -z "$href" ]; then echo "No related href found"; exit 1; fi
          case "$href" in
            http*) url="$href";;
            /repo_posts/*) url="https://tom-doerr.github.io$href";;
            /*) url="$BASE$href";;
            *) url="$BASE/$href";;
          esac
          # Retry to absorb deploy race
          ok=0; for i in 1 2 3 4 5; do
            if curl -fsS "$url" >/dev/null; then ok=1; break; fi
            sleep 3
          done
          [ "$ok" -eq 1 ] || (echo "Related URL failed after retries: $url" && exit 1)
      - name: Ensure single analytics script include
        run: |
          # Count Simple Analytics script occurrences on the sample post
          [ "$(grep -o 'scripts.simpleanalyticscdn.com' post2.html | wc -l)" -eq 1 ]
      - name: Check search index and site CSS exist
        run: |
          BASE=https://tom-doerr.github.io/repo_posts
          curl -fsS "$BASE/assets/search-index.json" | head -c 2 >/dev/null
          curl -fsS "$BASE/assets/css/site.css" | head -n 1
