name: RSS Smoke Check

on:
  workflow_run:
    workflows: ["Deploy Jekyll site"]
    types: ["completed"]

jobs:
  verify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check homepage
        run: |
          curl -fsS https://tom-doerr.github.io/repo_posts/
      - name: Check feed
        run: |
          curl -fsS https://tom-doerr.github.io/repo_posts/feed.xml | head -n 5
      - name: Check a sample post has image and index link
        run: |
          BASE=https://tom-doerr.github.io/repo_posts
          curl -fsS "$BASE/2025/10/21/julien040-anyquery.html" | tee post.html >/dev/null
          grep -q 'class="post-image"' post.html
          grep -q 'View on index' post.html
      - name: Check a sample post shows Related repos
        run: |
          BASE=https://tom-doerr.github.io/repo_posts
          curl -fsS "$BASE/2025/10/26/Tyrrrz-YoutubeExplode.html" | tee post2.html >/dev/null
          grep -q 'Related repos' post2.html
          grep -q '<ul class="related-list">' post2.html
      - name: Check search index and site CSS exist
        run: |
          BASE=https://tom-doerr.github.io/repo_posts
          curl -fsS "$BASE/assets/search-index.json" | head -c 2 >/dev/null
          curl -fsS "$BASE/assets/css/site.css" | head -n 1
